apiVersion: v1
kind: Service
metadata:
  name: aggregator
  labels:
    app: aggregator
spec:
  ports:
  - name: fluentd-tcp
    port: 24224
    protocol: TCP
    targetPort: 24224
  - name: fluentd-udp
    port: 24224
    protocol: UDP
    targetPort: 24224
    #  - name: fluentd-debug
    #    port: 8888
    #    protocol: TCP
    #    targetPort: 8888
    #  selector:
    #    app: fluentd
    #    app: aggregator
