apiVersion: v1
kind: Service
metadata:
  name: aggregator
  labels:
    app: aggregator
spec:
  ports:
  - protocol: TCP
    name: fluentd-port
    portL: 24224
    targetPort: 24224
  selector:
    app: aggregator
