kind: ConfigMap
apiVersion: v1
metadata:
  name: forwarder-fluentd-config
data:
  #
  # You can put multiple files if needed. Fluentd will read all of them
  # Config file name must be *.conf.
  #
  app.conf: |-
    <source>
      @type tail
      path /var/log/app.log
      pos_file /var/log/app.log.pos
      tag app.log
      <parse>
        @type json
      </parse>
    </source>

    <filter **>
      @type insert_id
    </filter>

    <match app.**>
      @type forward
      <server>
        name aggregator
        host "#{ENV['AGGREGATOR_SERVICE_HOST']}"
        port 24224
      </server>
    </match>

    <match **>
      @type stdout
    </match>
